export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CLEAR_ERRORS_REGISTER_STREAMER = 'CLEAR_ERRORS_REGISTER_STREAMER'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'update_password_request'
export const UPDATE_PASSWORD_SUCCESS = 'update_password_success'
export const UPDATE_PASSWORD_FAILURE = 'update_password_failure'
export const UPDATE_PASSWORD_RESET = 'update_password_reset'

export const FORGOT_PASSWORD_REQUEST = 'forgot_password_request'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_reset'
export const FORGOT_PASSWORD_FAILURE = 'forgot_password_failure'

export const RESET_PASSWORD_REQUEST = 'reset_password_request'
export const RESET_PASSWORD_SUCCESS = 'reset_password_success'
export const RESET_PASSWORD_FAILURE = 'reset_password_failure'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const REGISTER_STREAMER_SUCCESS = 'REGISTER_STREAMER_SUCCESS'
export const REGISTER_STREAMER_REQUEST = 'REGISTER_STREAMER_REQUEST'
export const REGISTER_STREAMER_FAIL = 'REGISTER_STREAMER_FAIL'
export const REGISTER_STREAMER_RESET_REGISTER_STREAMER =
  'REGISTER_STREAMER_RESET_REGISTER_STREAMER'

export const LOAD_STREAMER_REQUEST = 'LOAD_STREAMER_REQUEST'
export const LOAD_STREAMER_SUCCESS = 'LOAD_STREAMER_SUCCESS'
export const LOAD_STREAMER_FAIL = 'LOAD_STREAMER_FAIL'

export const UPDATE_PROFILE_STREAMER_REQUEST = 'UPDATE_PROFILE_STREAMER_REQUEST'
export const UPDATE_PROFILE_STREAMER_RESET = 'UPDATE_PROFILE_STREAMER_RESET'
export const UPDATE_PROFILE_STREAMER_SUCCESS = 'UPDATE_PROFILE_STREAMER_SUCCESS'
export const UPDATE_PROFILE_STREAMER_FAILURE = 'UPDATE_PROFILE_STREAMER_FAILURE'

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL'
export const CLEAR_LOAD_DATA_FAIL = 'CLEAR_LOAD_DATA_FAIL'

export const LOAD_DATA_STREAM_REQUEST = 'LOAD_DATA_STREAM_REQUEST'
export const LOAD_DATA_STREAM_SUCCESS = 'LOAD_DATA_STREAM_SUCCESS'
export const LOAD_DATA_STREAM_FAIL = 'LOAD_DATA_STREAM_FAIL'
export const CLEAR_LOAD_DATA_STREAM_FAIL = 'CLEAR_LOAD_DATA_STREAM_FAIL'
