export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CLEAR_ERRORS_REGISTER_STREAMER = 'CLEAR_ERRORS_REGISTER_STREAMER'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const UPDATE_PASSWORD_REQUEST = 'update_password_request'
export const UPDATE_PASSWORD_SUCCESS = 'update_password_success'
export const UPDATE_PASSWORD_FAILURE = 'update_password_failure'
export const UPDATE_PASSWORD_RESET = 'update_password_reset'

export const FORGOT_PASSWORD_REQUEST = 'forgot_password_request'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_reset'
export const FORGOT_PASSWORD_FAILURE = 'forgot_password_failure'

export const RESET_PASSWORD_REQUEST = 'reset_password_request'
export const RESET_PASSWORD_SUCCESS = 'reset_password_success'
export const RESET_PASSWORD_FAILURE = 'reset_password_failure'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const REGISTER_STREAMER_SUCCESS = 'REGISTER_STREAMER_SUCCESS'
export const REGISTER_STREAMER_REQUEST = 'REGISTER_STREAMER_REQUEST'
export const REGISTER_STREAMER_FAIL = 'REGISTER_STREAMER_FAIL'
export const REGISTER_STREAMER_RESET_REGISTER_STREAMER =
  'REGISTER_STREAMER_RESET_REGISTER_STREAMER'

export const LOAD_STREAMER_REQUEST = 'LOAD_STREAMER_REQUEST'
export const LOAD_STREAMER_SUCCESS = 'LOAD_STREAMER_SUCCESS'
export const LOAD_STREAMER_FAIL = 'LOAD_STREAMER_FAIL'

export const GET_STREAMER_INTRODUCE_REQUEST = 'GET_STREAMER_INTRODUCE_REQUEST'
export const GET_STREAMER_INTRODUCE_SUCCESS = 'GET_STREAMER_INTRODUCE_SUCCESS'
export const GET_STREAMER_INTRODUCE_FAIL = 'GET_STREAMER_INTRODUCE_FAIL'
export const CLEAR_GET_STREAMER_INTRODUCE_FAIL =
  'CLEAR_GET_STREAMER_INTRODUCE_FAIL'
export const CLEAR_GET_STREAMER_INTRODUCE_SUCCESS =
  'CLEAR_GET_STREAMER_INTRODUCE_SUCCESS'

export const UPDATE_PROFILE_STREAMER_REQUEST = 'UPDATE_PROFILE_STREAMER_REQUEST'
export const UPDATE_PROFILE_STREAMER_RESET = 'UPDATE_PROFILE_STREAMER_RESET'
export const UPDATE_PROFILE_STREAMER_SUCCESS = 'UPDATE_PROFILE_STREAMER_SUCCESS'
export const UPDATE_PROFILE_STREAMER_FAILURE = 'UPDATE_PROFILE_STREAMER_FAILURE'

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL'
export const CLEAR_LOAD_DATA_FAIL = 'CLEAR_LOAD_DATA_FAIL'

export const LOAD_DATA_STREAM_REQUEST = 'LOAD_DATA_STREAM_REQUEST'
export const LOAD_DATA_STREAM_SUCCESS = 'LOAD_DATA_STREAM_SUCCESS'
export const LOAD_DATA_STREAM_FAIL = 'LOAD_DATA_STREAM_FAIL'
export const CLEAR_LOAD_DATA_STREAM_FAIL = 'CLEAR_LOAD_DATA_STREAM_FAIL'

export const NEW_POST_REQUEST = 'NEW_POST_REQUEST'
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'
export const CLEAR_NEW_POST_FAIL = 'CLEAR_NEW_POST_FAIL'

export const LOAD_POST_USER_REQUEST = 'LOAD_POST_USER_REQUEST'
export const LOAD_POST_USER_SUCCESS = 'LOAD_POST_USER_SUCCESS'
export const LOAD_POST_USER_FAIL = 'LOAD_POST_USER_FAIL'
export const CLEAR_LOAD_POST_USER_FAIL = 'CLEAR_LOAD_POST_USER_FAIL'

export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL'
export const CLEAR_GET_ALL_POST_FAIL = 'CLEAR_GET_ALL_POST_FAIL'
export const RESET_CREATE_POST = 'RESET_CREATE_POST'

export const LOAD_POST_ID_REQUEST = 'LOAD_POST_ID_REQUEST'
export const LOAD_POST_ID_SUCCESS = 'LOAD_POST_ID_SUCCESS'
export const LOAD_POST_ID_FAIL = 'LOAD_POST_ID_FAIL'
export const CLEAR_LOAD_POST_ID_FAIL = 'CLEAR_LOAD_POST_ID_FAIL'

export const DELETE_POST_ID_SUCCESS = 'DELETE_POST_ID_SUCCESS'
export const DELETE_POST_ID_FAIL = 'DELETE_POST_ID_FAIL'
export const CLEAR_DELETE_POST_ID = 'CLEAR_DELETE_POST_ID'

export const GET_CATEGORY_POST_REQUEST = 'GET_CATEGORY_POST_REQUEST'
export const GET_CATEGORY_POST_SUCCESS = 'GET_CATEGORY_POST_SUCCESS'
export const GET_CATEGORY_POST_FAIL = 'GET_CATEGORY_POST_FAIL'
export const CLEAR_GET_CATEGORY_POST_FAIL = 'CLEAR_GET_CATEGORY_POST_FAIL'

export const GET_CATEGORY_POST_BY_ID_REQUEST = 'GET_CATEGORY_POST_BY_ID_REQUEST'
export const GET_CATEGORY_POST_BY_ID_SUCCESS = 'GET_CATEGORY_POST_BY_ID_SUCCESS'
export const GET_CATEGORY_POST_BY_ID_FAIL = 'GET_CATEGORY_POST_BY_ID_FAIL'
export const CLEAR_GET_CATEGORY_POST_BY_ID_FAIL =
  'CLEAR_GET_CATEGORY_POST_BY_ID_FAIL'

export const LOAD_CATEGORY_POST_ID_REQUEST = 'LOAD_CATEGORY_POST_ID_REQUEST'
export const LOAD_CATEGORY_POST_ID_SUCCESS = 'LOAD_CATEGORY_POST_ID_SUCCESS'
export const LOAD_CATEGORY_POST_ID_FAIL = 'LOAD_CATEGORY_POST_ID_FAIL'
export const CLEAR_LOAD_CATEGORY_POST_ID_FAIL =
  'CLEAR_LOAD_CATEGORY_POST_ID_FAIL'

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'
export const CLEAR_NEW_COMMENT_FAIL = 'CLEAR_NEW_COMMENT_FAIL'

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL'
export const CLEAR_GET_COMMENT_FAIL = 'CLEAR_GET_COMMENT_FAIL'
export const RESET_CREATE_COMMENT = 'RESET_CREATE_POST'

export const DELETE_COMMENT_ID_SUCCESS = 'DELETE_COMMENT_ID_SUCCESS'
export const DELETE_COMMENT_ID_FAIL = 'DELETE_COMMENT_ID_FAIL'

export const LOAD_COMMENT_POST_ID_REQUEST = 'LOAD_COMMENT_POST_ID_REQUEST'
export const LOAD_COMMENT_POST_ID_SUCCESS = 'LOAD_COMMENT_POST_ID_SUCCESS'
export const LOAD_COMMENT_POST_ID_FAIL = 'LOAD_COMMENT_POST_ID_FAIL'
export const CLEAR_LOAD_COMMENT_POST_ID_FAIL = 'CLEAR_LOAD_COMMENT_POST_ID_FAIL'

export const GET_CATEGORY_REPORT_REQUEST = 'GET_CATEGORY_REPORT_REQUEST'
export const GET_CATEGORY_REPORT_SUCCESS = 'GET_CATEGORY_REPORT_SUCCESS'
export const GET_CATEGORY_REPORT_FAIL = 'GET_CATEGORY_REPORT_FAIL'
export const CLEAR_GET_CATEGORY_REPORT_FAIL = 'CLEAR_GET_CATEGORY_REPORT_FAIL'

export const NEW_REPORT_REQUEST = 'NEW_REPORT_REQUEST'
export const NEW_REPORT_SUCCESS = 'NEW_REPORT_SUCCESS'
export const NEW_REPORT_FAIL = 'NEW_REPORT_FAIL'
export const CLEAR_NEW_REPORT_FAIL = 'CLEAR_NEW_REPORT_FAIL'
export const RESET_CREATE_REPORT = 'RESET_CREATE_REPORT'

export const FOLLOW_STREAMER_REQUEST = 'FOLLOW_STREAMER_REQUEST'
export const FOLLOW_STREAMER_SUCCESS = 'FOLLOW_STREAMER_SUCCESS'
export const FOLLOW_STREAMER_FAIL = 'FOLLOW_STREAMER_FAIL'
export const CLEAR_FOLLOW_STREAMER_FAIL = 'CLEAR_FOLLOW_STREAMER_FAIL'
export const RESET_FOLLOW_STREAMER_SUCCESS = 'RESET_FOLLOW_STREAMER_SUCCESS'

export const SEARCH_STREAMER_REQUEST = 'SEARCH_STREAMER_REQUEST'
export const SEARCH_STREAMER_SUCCESS = 'SEARCH_STREAMER_SUCCESS'
export const SEARCH_STREAMER_FAIL = 'SEARCH_STREAMER_FAIL'
export const CLEAR_SEARCH_STREAMER_FAIL = 'CLEAR_SEARCH_STREAMER_FAIL'
export const CLEAR_SEARCH_STREAMER_SUCCESS = 'CLEAR_SEARCH_STREAMER_SUCCESS'

export const NEW_REPORT_STREAMER_REQUEST = 'NEW_REPORT_STREAMER_REQUEST'
export const NEW_REPORT_STREAMER_SUCCESS = 'NEW_REPORT_STREAMER_SUCCESS'
export const NEW_REPORT_STREAMER_FAIL = 'NEW_REPORT_STREAMER_FAIL'
export const CLEAR_NEW_REPORT_STREAMER_FAIL = 'CLEAR_NEW_REPORT_STREAMER_FAIL'
export const RESET_CREATE_REPORT_STREAMER = 'RESET_CREATE_REPORT_STREAMER'

export const GET_ALL_URL_STREAMER_REQUEST = 'GET_ALL_URL_STREAMER_REQUEST'
export const GET_ALL_URL_STREAMER_SUCCESS = 'GET_ALL_URL_STREAMER_SUCCESS'
export const GET_ALL_URL_STREAMER_FAIL = 'GET_ALL_URL_STREAMER_FAIL'
export const CLEAR_GET_ALL_URL_STREAMER_FAIL = 'CLEAR_GET_ALL_URL_STREAMER_FAIL'
